modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="infernium"
version="1.0"
displayName="Infernium"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalidid/"
logoFile="examplemod.png"
credits="ShibePlanet, LucasTM and Stanford47"
authors="ShibePlanet, LucasTM and Stanford47"
description='''
Infernium
Programmed by Shibeplanet and Stanford47.
Art by LucasTM.
'''

